# Generated by Django 5.0.3 on 2024-06-15 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0001_initial'),
        ('endereco', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14)),
                ('especializacao', models.CharField(choices=[('massas', 'Massas'), ('pizza', 'Pizza'), ('carnes', 'Carnes')], max_length=10)),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contato.contato')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
