# Generated by Django 5.0.3 on 2024-06-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0007_alter_restaurante_especializacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurante',
            name='especializacao',
            field=models.CharField(choices=[('carnes', 'Carnes'), ('massas', 'Massas'), ('pizza', 'Pizza')], max_length=10),
        ),
    ]
