# Generated by Django 5.0.3 on 2024-03-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0002_alter_contato_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='nome_contato',
        ),
    ]
