# Generated by Django 5.0.3 on 2024-03-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0003_alter_endereco_cep_alter_endereco_complemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, default='---', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(blank=True),
        ),
    ]
