# Generated by Django 5.0.3 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0005_alter_endereco_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
