# Generated by Django 5.0.3 on 2024-03-30 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0006_alter_endereco_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='nome',
            new_name='nome_endereco',
        ),
    ]
