# Generated by Django 5.0.3 on 2024-06-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregador',
            name='cpf',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='entregador',
            name='disponibilidade',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('desativado', 'Desativado'), ('ocupado', 'Ocupado')], default='desativado', max_length=10),
        ),
        migrations.AddField(
            model_name='entregador',
            name='placa',
            field=models.CharField(default='', max_length=8),
        ),
    ]
