# Generated by Django 5.0.3 on 2024-06-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0004_alter_entregador_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='disponibilidade',
            field=models.CharField(choices=[('desativado', 'Desativado'), ('disponivel', 'Disponível'), ('ocupado', 'Ocupado')], default='disponível', max_length=10),
        ),
    ]
