# Generated by Django 5.0.3 on 2024-06-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0007_alter_entregador_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='disponibilidade',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('desativado', 'Desativado'), ('ocupado', 'Ocupado')], default='disponível', max_length=10),
        ),
    ]
