# Generated by Django 5.0.3 on 2024-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0008_alter_entregador_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='disponibilidade',
            field=models.CharField(choices=[('desativado', 'Desativado'), ('ocupado', 'Ocupado'), ('disponivel', 'Disponível')], default='disponível', max_length=10),
        ),
    ]
