# Generated by Django 5.0.3 on 2024-06-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0020_alter_entregador_disponibilidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregador',
            name='disponibilidade',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponivel', 'Disponível'), ('desativado', 'Desativado')], default='disponível', max_length=10),
        ),
    ]
