# Generated by Django 5.0.3 on 2024-03-30 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contato', '0003_rename_nome_contato_nome_contato'),
        ('endereco', '0007_rename_nome_endereco_nome_endereco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contato.contato')),
                ('endereco', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='endereco.endereco')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
