# Generated by Django 5.0.3 on 2024-06-15 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='produto.produto')),
                ('produtos', models.ManyToManyField(related_name='combo_produtos', to='produto.produto')),
            ],
            bases=('produto.produto',),
        ),
    ]
