# Generated by Django 5.0.3 on 2024-06-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meio_pagamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meiopagamento',
            name='valor_trasacionado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
