# Generated by Django 5.0.3 on 2024-06-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0001_initial'),
        ('pedido', '0002_pedido_produtos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='combos',
            field=models.ManyToManyField(related_name='pedidos', to='combo.combo'),
        ),
    ]
