# Generated by Django 5.0.3 on 2024-06-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregador', '0013_alter_entregador_disponibilidade'),
        ('pedido', '0005_pedido_entregador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='entregador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='entregador.entregador'),
        ),
    ]
