# Generated by Django 5.0.3 on 2024-06-15 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meio_pagamento', '0002_alter_meiopagamento_valor_trasacionado'),
        ('pedido', '0006_alter_pedido_entregador'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='meio_pagamento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='meio_pagamento.meiopagamento'),
        ),
    ]
