# Generated by Django 5.0.3 on 2024-06-15 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meio_pagamento', '0002_alter_meiopagamento_valor_trasacionado'),
        ('pedido', '0007_pedido_meio_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='meio_pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='meio_pagamento.meiopagamento'),
        ),
    ]
