# Generated by Django 5.0.3 on 2024-06-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combo', '0001_initial'),
        ('pedido', '0008_alter_pedido_meio_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='combos',
            field=models.ManyToManyField(null=True, related_name='pedidos', to='combo.combo'),
        ),
    ]
